### ISSUE TITLE
A legújabb WorldGaurdal nem működik.

### ISSUE THREAD

**Issue by andris155** [TryHardDood/myZone#1]
https://dev.bukkit.org/bukkit-plugins/worldguard/files/48-world-guard-6-2-for-mc-up-to-1-11/
```
[04:01:20] [Server thread/INFO]: [myZone] Enabling myZone v1.0-SNAPSHOT
[04:01:20] [Server thread/INFO]: [myZone v1.0-SNAPSHOT] Starting...
[04:01:20] [Server thread/WARN]: [ myZone] Failed to find version enum for 'org.bukkit.craftbukkit.v1_11_R1'/'v1_11_R1.'
[04:01:20] [Server thread/INFO]: [ myZone] Generating dynamic constant...
[04:01:20] [Server thread/INFO]: [myZone v1.0-SNAPSHOT] Trying to hook WorldGuard...
[04:01:20] [Server thread/INFO]: [myZone v1.0-SNAPSHOT] WorldGuard (v6.2.1-SNAPSHOT;1695-6e56763) successfully hooked.
[04:01:20] [Server thread/INFO]: [myZone v1.0-SNAPSHOT] Creating commands...
[04:01:20] [Server thread/INFO]: [myZone v1.0-SNAPSHOT] Commands successfully created.
[04:01:20] [Server thread/INFO]: [myZone v1.0-SNAPSHOT] Hooking events...
[04:01:20] [Server thread/INFO]: [myZone v1.0-SNAPSHOT] Events successfully hooked.
[04:01:20] [Server thread/INFO]: [myZone v1.0-SNAPSHOT] Loading configuration file...
[04:01:20] [Server thread/ERROR]: Error occurred while enabling myZone v1.0-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.flags.DefaultFlag.fuzzyMatchFlag(Ljava/lang/String;)Lcom/sk89q/worldguard/protection/flags/Flag;
	at hu.tryharddood.myzone.Properties.loadConfiguration(Properties.java:150) ~[?:?]
	at hu.tryharddood.myzone.myZone.onEnable(myZone.java:94) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.jar:git-Paper-958]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.jar:git-Paper-958]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.jar:git-Paper-958]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:377) [patched_1.11.jar:git-Paper-958]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:327) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:433) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:394) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:332) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.jar:git-Paper-958]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:599) [patched_1.11.jar:git-Paper-958]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[04:01:20] [Server thread/INFO]: [myZone] Disabling myZone v1.0-SNAPSHOT
```

**Comment by benjaminforras** [comment]
Fixed in https://github.com/TryHardDood/myZone/commit/88e8c9f07c6b8df2c98a9f5ea551a96dc3da8b76
