### ISSUE TITLE
plugman unloadnál írta ezt a hibát nem tudom, hogy ez hiba-e

### ISSUE THREAD

**Issue by andris155** [TryHardDood/myZone#10]
Ha jól értelmezem ez lenne az amikor valaki területére lépünk és szöveget ír? Nekem ez a szöveg egyébként nem működik, ha a Title beállítás az lenne a konfigban.
Az újraindítás megoldotta a hibát egyébként.
```
[16:07:03] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to WorldGuard v6.2.1-SNAPSHOT;1695-6e56763
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.jar:git-Paper-976]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.11.jar:git-Paper-976]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.jar:git-Paper-976]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.jar:git-Paper-976]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:610) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.jar:git-Paper-976]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-976]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:410) ~[patched_1.11.jar:git-Paper-976]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:129) ~[patched_1.11.jar:git-Paper-976]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:112) ~[patched_1.11.jar:git-Paper-976]
	at hu.tryharddood.myzone.Listeners.rListener.updateRegions(rListener.java:87) ~[?:?]
	at hu.tryharddood.myzone.Listeners.rListener.onPlayerMove(rListener.java:47) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor509.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.jar:git-Paper-976]
	... 16 more
```

**Comment by benjaminforras** [comment]
PlugMan-t nem szeretjük :)
A config fájl nem frissül, ha frissíted a plugint, ezt neked manuálisan kell állítanod.
Itt megtalálod a legfrissebb config fájlt: https://raw.githubusercontent.com/TryHardDood/myZone/v1.1/src/main/resources/config.yml
