### ISSUE TITLE
myzone hiba (nem tudom mitől)

### ISSUE THREAD

**Issue by andris155** [TryHardDood/myZone#2]
```
[19:39:48] [Timer-2/INFO]: [WorldGuard] Region data changes made in 'world' have been background saved
[19:39:48] [Server thread/WARN]: com.sk89q.worldguard.protection.managers.storage.StorageException: Failed to rename temporary regions file to /home/minecraft/multicraft/servers/server5/plugins/WorldGuard/worlds/world/regions.yml
[19:39:48] [Server thread/WARN]: 	at com.sk89q.worldguard.protection.managers.storage.file.YamlRegionFile.saveAll(YamlRegionFile.java:242)
[19:39:48] [Server thread/WARN]: 	at com.sk89q.worldguard.protection.managers.RegionManager.save(RegionManager.java:108)
[19:39:48] [Server thread/WARN]: 	at hu.tryharddood.myzone.Util.WGWrapper.saveAll(WGWrapper.java:345)
[19:39:48] [Server thread/WARN]: 	at hu.tryharddood.myzone.Commands.MainCommand$4.interact(MainCommand.java:129)
[19:39:48] [Server thread/WARN]: 	at hu.tryharddood.myzone.MenuBuilder.inventory.InventoryListener.onInventoryClick(InventoryListener.java:115)
[19:39:48] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor498.execute(Unknown Source)
[19:39:48] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
[19:39:48] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[19:39:48] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[19:39:48] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[19:39:48] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[19:39:48] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1883)
[19:39:48] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33)
[19:39:48] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10)
[19:39:48] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[19:39:48] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[19:39:48] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[19:39:48] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[19:39:48] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817)
[19:39:48] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[19:39:48] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749)
[19:39:48] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648)
```

**Comment by benjaminforras** [comment]
A problémát a WorldGuard okozza, valamiért nem sikerült elmenteni a `/home/minecraft/multicraft/servers/server5/plugins/WorldGuard/worlds/world/regions.yml` fájt.

Itt dobja a WorldGuard a hibát: [YamlRegionFile.java#L242](https://github.com/sk89q/WorldGuard/blob/master/worldguard-legacy/src/main/java/com/sk89q/worldguard/protection/managers/storage/file/YamlRegionFile.java#L242)
