### ISSUE TITLE
Leállítás/indítás hiba 1.12-vel

### ISSUE THREAD

**Issue by andris155** [TryHardDood/myZone#26]
## What steps will reproduce the problem?  
1. /stop

## What were you expecting to happen? What happened instead?  
Hibát ír a plugin.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
![kepkivagas](https://user-images.githubusercontent.com/8324198/27108882-d76e280e-509f-11e7-9775-541905f8f45c.PNG)

## What Spigot version are you using? *Type /version*  
![kepkivagas](https://user-images.githubusercontent.com/8324198/27108894-f0580e84-509f-11e7-847d-8fc2b9457814.PNG)

## What plugins are you using? *Type /plugins*  
Ez, ha fontos elküldöm privátban.

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
```
[01:06:03] [Server thread/ERROR]: Error occurred while disabling myZone v1.1.167 (Is it up to date?)
java.lang.NullPointerException: null
	at hu.tryharddood.myzone.myZone.onDisable(myZone.java:118) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.jar:git-Paper-1122]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.12.jar:git-Paper-1122]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [patched_1.12.jar:git-Paper-1122]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [patched_1.12.jar:git-Paper-1122]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:347) [patched_1.12.jar:git-Paper-1122]
	at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:485) [patched_1.12.jar:git-Paper-1122]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:700) [patched_1.12.jar:git-Paper-1122]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```
```
14.06 01:27:31 [Server] INFO Enabling myZone v1.1.167
14.06 01:27:31 [Server] WARN Failed to find version enum for 'org.bukkit.craftbukkit.v1_12_R1'/'v1_12_R1.'
```

## Additional information?  *(Did it work in previous versions? etc.)*
![kepkivagas](https://user-images.githubusercontent.com/8324198/27108934-3613b248-50a0-11e7-8c52-7b14d17f8bf6.PNG)
![kepkivagas](https://user-images.githubusercontent.com/8324198/27108953-4a6d9880-50a0-11e7-873e-c8323c75da5c.PNG)

**Comment by benjaminforras** [comment]
Ettől a hibától még ugyan úgy működik a plugin?
Amint lesz időm utána nézek.

**Comment by andris155** [comment]
nem működik

**Comment by benjaminforras** [comment]
Még ma kijavítom. Köszi, hogy jelezted

**Comment by andris155** [comment]
![kepkivagas](https://user-images.githubusercontent.com/8324198/27133165-92f7f5c0-5111-11e7-930a-b4c30a8bc3ee.PNG)
![kepkivagas](https://user-images.githubusercontent.com/8324198/27133229-c65f9206-5111-11e7-959b-8b2518a28eb6.PNG)
Ezt az MCVersion dolgot amúgy én meg sem  találtam, és az mvn-nek is problémája van vele.

**Comment by benjaminforras** [comment]
Valószínűleg azért mert, viszonylag régi a kód. Javítani fogom.

**Comment by benjaminforras** [comment]
Kérlek próbáld meg ezzel a verzióval: https://github.com/TryHardDood/myZone/releases/latest
